### ISSUE TITLE
Remove .pyc files and template DB password

### ISSUE THREAD

**Issue by eugene-chow** [CloudCommandos/shares#8]
- [x] [`.pyc` files](https://github.com/CloudCommandos/shares/tree/0c9da70481c3fc6aa6b9c78520ea7da9d1c378de/Monitoring%20in%20a%20Box/WebGUI/backend/backend_server) are compiled Python scripts. Remove them.
   - [x] Add a `.gitignore` so that future `.pyc` files and `.vault` files don't get committed
- [x] Template the [DB password](https://github.com/CloudCommandos/shares/blob/0c9da70481c3fc6aa6b9c78520ea7da9d1c378de/Monitoring%20in%20a%20Box/WebGUI/backend/backend_server/IssConfig.py) so that an arbitrary password can be configured when the Ansible script is run.
   - [x] Update the [Ansible script](https://github.com/CloudCommandos/shares/blob/master/Monitoring%20in%20a%20Box/Ansible/roles/mib_setup/tasks/set_up_postgresql.yaml) that sets the DB password.

**Comment by alexling92** [comment]
Resolved in latest commit
